### ISSUE TITLE
ExpandoObjects leak memory when used as an IDictionary<string,object> to add new properties

### ISSUE THREAD

**Issue by mstijak** [robconery/massive#216]
I encountered out of memory problems with a long running windows service. After memory profiling we found very large number of objects of type Microsoft.CSharp.RuntimeBinder.Semantics.AggregateDeclaration which brought us to 
this issue:
https://connect.microsoft.com/VisualStudio/feedback/details/783541/expandoobjects-leak-memory-when-used-as-an-idictionary-string-object-to-add-new-properties

I would say this is really a .NET bug, but Massive uses ExpandoObjects exactly in described manner and I guess this causes memory leaks.

I'm wondering if you're aware of this issue and maybe have an advice on how to tackle this issue?

**Comment by robconery** [comment]
Hi Marko - I haven’t had reports of this issue yet… the one thing I might suggest is killing the objects in a more timely manner, maybe treating them as DTOs or something to fill another class?

**Comment by mstijak** [comment]
Update:
It seems that this is a .NET bug. I have reported it here:
https://connect.microsoft.com/VisualStudio/feedback/details/1126334/expandoobjects-datetime-memory-leak.
It's very strange.
